version: 2
updates:
  # Maintain dependencies for npm/yarn
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - javascript
      - dependencies

  # Maintain dependencies for Cloud Functions
  - package-ecosystem: npm
    directory: "/cloud/functions"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - functions
      - dependencies
