version: 2
updates:
  # Maintain dependencies for github-actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  # Maintain dependencies for npm/yarn
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - javascript
      - dependencies
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      trpc:
        patterns:
          - "@trpc/*"

  # Maintain dependencies for Cloud Functions
  - package-ecosystem: npm
    directory: "/cloud/functions"
    schedule:
      interval: weekly
    labels:
      - functions
      - dependencies
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
