version: 2
updates:
  # Maintain dependencies for github-actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  # Maintain dependencies for npm/yarn
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - javascript
      - dependencies

  # Maintain dependencies for Cloud Functions
  - package-ecosystem: npm
    directory: "/cloud/functions"
    schedule:
      interval: monthly
    labels:
      - functions
      - dependencies
