name: Lint and Build Functions
on:
  pull_request:
    paths: ["cloud/functions/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.x

jobs:
  build:
    name: Run lint and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloud/functions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Code Linting
        run: yarn lint --max-warnings=0

      - name: Run build
        run: yarn build
