name: Cleanup Old Cache
on:
  workflow_run:
    workflows: ["Cache Node.js dependencies", "Lockfile Maintenance"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-yarn:
    name: Cleanup frontend cache
    uses: KenTandrian/workflows/.github/workflows/cleanup.yml@main
    with:
      name: Yarn
      pattern: node-cache-Linux-yarn-

  cleanup-npm:
    name: Cleanup backend cache
    uses: KenTandrian/workflows/.github/workflows/cleanup.yml@main
    with:
      name: NPM
      pattern: node-cache-Linux-npm-
