name: Lockfile Maintenance (Cloud)
on: workflow_dispatch

jobs:
  run:
    name: Run workflow
    uses: KenTandrian/workflows/.github/workflows/lockfile.yml@main
    permissions:
      contents: write
    with:
      package-manager: yarn
      working-directory: ./cloud/functions
    secrets: inherit
