name: Pull Request Reviewer

on: pull_request_target

permissions:
  pull-requests: write
  contents: write
  repository-projects: read

jobs:
  review-dependabot-pr:
    name: PR Review
    uses: KenTandrian/workflows/.github/workflows/dependabot-reviewer.yml@main
